### ISSUE TITLE
Docker - ModuleNotFoundError: No module named 'nfc'

### ISSUE THREAD

**Issue by sauloonze** [bkupidura/nfc2mqtt#1]
Hello,

I am trying to run the project in docker and I am getting an error.

I am running the docker using the following command:
`root@docker:/srv/nfc2mqtt# docker run -d --name nfc2mqtt -v /srv/nfc2mqtt/config/config.yaml:/config.yaml --device /dev/bus/usb/002/002 ghcr.io/bkupidura/nfc2mqtt:latest`

My container log error is:
`Traceback (most recent call last):
  File "/usr/local/bin/nfc2mqtt", line 5, in <module>
    from nfc2mqtt.service import main
  File "/usr/local/lib/python3.10/site-packages/nfc2mqtt/service/__init__.py", line 11, in <module>
    import nfc
ModuleNotFoundError: No module named 'nfc'`

Could you help me to find a solution?

Thanks

**Comment by bkupidura** [comment]
Hey,

Thanks for PR. Merged.

Also rebuilded docker image.
